export const jurisdiction = [
  "ny.taobao.com",
  "wt.taobao.com",
  "gushi.taobao.com",
  "ebook.taobao.com",
  "music.taobao.com",
  "waimai.taobao.com",
  "dianying.taobao.com",
  "yun.taobao.com",
  "wan.taobao.com",
  "trip.taobao.com",
  "game.taobao.com",
  "paimai.taobao.com",
  "vip.taobao.com",
  "gongyi.taobao.com",
  "qinglv.taobao.com",
  "zhoumo.taobao.com",
  "shenghuo.taobao.com",
  "dapei.taobao.com",
  "xue.taobao.com",
  "wenyu.taobao.com",
  "baoxian.taobao.com",
  "fang.taobao.com",
  "life.taobao.com",
  "1.life.taobao.com",
  "hunban.taobao.com",
  "ktv.taobao.com",
  "enjoy.taobao.com",
  "caipiao.taobao.com",
  "licai.taobao.com",
  "baobao.taobao.com",
  "hi.taobao.com",
  "2.taobao.com",
  "china.taobao.com",
  "chi.taobao.com",
  "world.chi.taobao.com",
  "star.taobao.com",
  "jiadian.taobao.com",
  "baihuo.taobao.com",
  "sport.taobao.com",
  "home.taobao.com",
  "jia.taobao.com",
  "3c.taobao.com",
  "cdj.taobao.com",
  "car.taobao.com",
  "bling.taobao.com",
  "pei.taobao.com",
  "neiyi.taobao.com",
  "mei.taobao.com",
  "xie.taobao.com",
  "bao.taobao.com",
  "nanxie.taobao.com",
  "nanbao.taobao.com",
  "nvxie.taobao.com",
  "nvbao.taobao.com",
  "ye.taobao.com",
  "tese.taobao.com",
  "style.taobao.com",
  "acg.taobao.com",
  "life.taobao.com",
  "zhiyou.taobao.com",
  "try.taobao.com",
  "tiaoshi.chi.taobao.com",
  "china.taobao.com",
  "hitao.taobao.com",
  "tejia.taobao.com",
  "qiang.taobao.com",
  "qing.taobao.com",
  "ju.taobao.com",
  "detail.ju.taobao.com",
  "guang.taobao.com",
  "taotelaisi.taobao.com",
  "q.taobao.com",
  "pp.taobao.com",
  "nz.taobao.com",
  "nvren.taobao.com",
  "nanren.taobao.com",
  "zln.taobao.com",
  "taojinbi.taobao.com",
  "g.taobao.com",
  "item.taobao.com",
  "item.tiaoshi.taobao.com",
  "huiyuangou.uz.taobao.com",
  "scportal.taobao.com",

  "detail.tmall.com",
  "tmall.hk",
  "detail.tmall.hk",

  "detail.liangxinyao.com",
];

export const coupons = ["uland.taobao.com", "m.taobao.com"];

export const vipShop = ["detail.vip.com", "www.vipglobal.hk"];

export const jdcom = [
  "www.jd.com",
  "item.jd.com",
  "cartv.jd.com",
  "npcitem.jd.hk",
  "item.yiyaojd.com"
  // "e.jd.com", // 暂时屏蔽
];
